source "https://github.com/CocoaPods/Specs.git"

platform :ios, '11.0'
use_frameworks!

def shared_pods
    pod 'SygicUIKit', :git => 'https://github.com/Sygic/sygic-ui-kit-ios.git', :branch => 'feature/route-preview-controls', :commit => 'HEAD'
    pod 'SygicMaps'
    pod 'SygicMapsKit', :path => '../'
end

target 'SygicMapsKit_Example' do
    shared_pods
end

target 'SygicMapsKit_Tests' do
    shared_pods
    pod 'Quick', '~> 1.2.0', :inhibit_warnings => true
    pod 'Nimble', '~> 7.3.1', :inhibit_warnings => true
end

target 'SygicMapsKit_ExampleUITests' do
    shared_pods
end

target 'SygicMapsKit_UITests' do
    shared_pods
    pod 'KIF', :configurations => ['Debug']
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
            config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        end
    end
end
