source "ssh://git@git.sygic.com:7999/navi/cocoapods.git"
source "https://github.com/CocoaPods/Specs.git"

platform :ios, '10.0'
use_frameworks!

target 'SygicMapsKit_Example' do
    
  pod 'SygicMaps', '3.2.2'
  pod 'SygicUIKit', :git => 'https://github.com/Sygic/sygic-ui-kit-ios.git', :branch => 'develop', :commit => 'HEAD'
  pod 'SygicMapsKit', :path => '../'

  target 'SygicMapsKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0', :inhibit_warnings => true
    pod 'Nimble', '~> 7.3.1', :inhibit_warnings => true
    
  end
  
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
            config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        end
    end
end
