platform :ios, '10.0'
use_frameworks!

target 'SygicMapsKit_Example' do
  pod 'SygicUIKit', :git => 'https://github.com/Sygic/sygic-ui-kit-ios.git', :branch => 'develop', :commit => 'HEAD'
  pod 'SygicMapsKit', :path => '../'

  target 'SygicMapsKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
